#!/usr/bin/env bash

set -e

SCRIPTS_DIR="$(cd "$(dirname ${BASH_SOURCE[0]})/.." && pwd)"
for f in "${SCRIPTS_DIR}"/lib/*; do
  . "$f"
done

# Download and install openshift-install binary.
if ! command -v openshift-install > /dev/null; then
  curl -L https://github.com/openshift/installer/releases/download/v0.12.0/openshift-install-linux-amd64 -o openshift-install
  chmod +x openshift-install
  sudo mv openshift-install /usr/local/bin/
fi

if [[ -z "$ASSETS_DIR" ]]; then
  echo "ASSETS_DIR not set."
  exit 1
fi
if [[ -z "$CLUSTER_NAME" ]]; then
  echo "CLUSTER_NAME not set."
  exit 1
fi
if [[ "$(basename "$ASSETS_DIR")" != "$CLUSTER_NAME" ]]; then
  echo "ASSETS_DIR must end in \"$CLUSTER_NAME\"."
  exit 1
fi
if [[ -z "$PULL_SECRET" ]]; then
  echo "PULL_SECRET not set."
  exit 1
fi
INSTALL_CONFIG_FILE="${ASSETS_DIR}/install-config.yaml"

# Create openshift cluster using a predefined install config.
mkdir -p "$ASSETS_DIR"
cp "${SCRIPTS_DIR}/assets/$(basename "$INSTALL_CONFIG_FILE")" "$INSTALL_CONFIG_FILE"
sed -i "s/PULL_SECRET_REPLACEME/'$PULL_SECRET'/g" "$INSTALL_CONFIG_FILE"
sed -i "s/CLUSTER_NAME_REPLACEME/${CLUSTER_NAME}/g" "$INSTALL_CONFIG_FILE"
openshift-install --dir="$ASSETS_DIR" create cluster

check_cluster_available "$CLUSTER_NAME"
