#!/usr/bin/env bash

set -ex

SUDO=sudo
if [ -f /.dockerenv ]; then
  SUDO=
fi

$SUDO apt-get update
# jq, yq
$SUDO apt-get install -y jq
curl -Lo yq https://github.com/mikefarah/yq/releases/download/2.2.1/yq_linux_amd64
chmod +x yq
$SUDO mv yq /usr/local/bin/
# SDK
curl -Lo operator-sdk https://github.com/operator-framework/operator-sdk/releases/download/v0.5.0/operator-sdk-v0.5.0-x86_64-linux-gnu
chmod +x operator-sdk
$SUDO mv operator-sdk /usr/local/bin/
# helm
curl https://raw.githubusercontent.com/helm/helm/master/scripts/get | bash
# kubectl
curl -Lo kubectl https://storage.googleapis.com/kubernetes-release/release/v1.13.0/bin/linux/amd64/kubectl
chmod +x kubectl
$SUDO mv kubectl /usr/local/bin/
# minikube.
curl -Lo minikube https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
chmod +x minikube
$SUDO mv minikube /usr/local/bin/
