#!/usr/bin/env bash

set -ex

sudo apt-get update
# jq, yq
sudo apt-get install -y jq
curl -L https://github.com/mikefarah/yq/releases/download/2.2.1/yq_linux_amd64 -o yq
chmod +x yq
sudo mv yq /usr/local/bin/
# SDK
curl -L https://github.com/operator-framework/operator-sdk/releases/download/v0.5.0/operator-sdk-v0.5.0-x86_64-linux-gnu -o operator-sdk
chmod +x operator-sdk
sudo mv operator-sdk /usr/local/bin/
# helm
curl https://raw.githubusercontent.com/helm/helm/master/scripts/get | bash
# kubectl
sudo apt-get install -y apt-transport-https
curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -
echo "deb https://apt.kubernetes.io/ kubernetes-xenial main" | sudo tee -a /etc/apt/sources.list.d/kubernetes.list
sudo apt-get update
sudo apt-get install -y kubectl
# oc
OC_DIR="openshift-origin-client-tools-v3.11.0-0cbc58b-linux-64bit"
curl -L https://github.com/openshift/origin/releases/download/v3.11.0/${OC_DIR}.tar.gz -o oc.tar.gz
tar -zxOf oc.tar.gz ${OC_DIR}/oc > oc
chmod +x oc
sudo mv oc /usr/local/bin/
