#!/usr/bin/env bash

TMP_OLM="$(mktemp -d)"
# TODO(estroz): pin OLM version once we confirm a version works with all
# upstream operators.
OLM_VER="master"
git clone https://github.com/operator-framework/operator-lifecycle-manager.git \
  "$TMP_OLM" --branch "$OLM_VER" --single-branch
pushd "$TMP_OLM"
# Remove checkout once version is pinned.
git checkout eb7ad04e25a7e71ee3e19b324a2c35180166b3ce
NO_MINIKUBE=true make run-local
popd
