#!/usr/bin/env bash

for f in "$(cd "$(dirname ${BASH_SOURCE[0]})/.." && pwd)"/lib/*; do
  . "$f"
done

if [[ -z "$ASSETS_DIR" ]]; then
  echo "ASSETS_DIR not set."
  exit 1
fi

PW_FILE="kubeconfig-pass.txt"
gen_password > "$PW_FILE"
encrypt_kubeconfig "${ASSETS_DIR}/auth/kubeconfig" "$PW_FILE"
mv "${ASSETS_DIR}/auth/kubeconfig.enc" .
kubeconfig_to_s3 kubeconfig.enc community-operators-test
